#! /bin/sh

#pickup the xresource file from config directory
xrdb -I ~/.config/X11/.Xresources
#launch key demon
sxhkd -c ~/.config/bspwm/sxhkdrc &
#set ultrawide resolution
xrandr --output HDMI-1 --off --output DP-1 --mode 3440x1440
#set wallpaper
feh --bg-scale '/home/diego/.config/feh/mono.png' &

#defines monitors
bspc monitor -d terminal web coding debug files music misc process

bspc config border_width            1
bspc config window_gap              10
bspc config top_padding             45 
bspc config right_padding           25 
bspc config bottom_padding          25 
bspc config left_padding            25

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config normal_border_color     "#282C34"
bspc config focused_border_color    "#282C34"
bspc config presel_feedback_color   "#5C6370"

#startup applications
#bspc rule -a URxvt -o desktop='terminal' state=floating follow=on rectangle=1200x1000+150+100 && urxvt -e htop &
#bspc rule -a URxvt -o desktop='terminal' && urxvt &
#bspc rule -a URxvt desktop='terminal' follow=on
bspc rule -a Firefox desktop='web' follow=on
bspc rule -a '*:zathura' state=tiled
#bspc rule -a URxvt -o desktop='embedded' && urxvt -e nvim -O ~/Framework/test/{main,inits,interrupts}.c &

#launch Polybar
polybar mybar -r -c ~/.config/polybar/config
