#! /bin/sh

#launch key demon
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
#set wallpaper
feh --bg-scale "$HOME/.config/wallpapers/mono.png" &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width            1
bspc config window_gap              10

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config normal_border_color     "#282C34"
bspc config focused_border_color    "#000000"
bspc config presel_feedback_color   "#000000"

#launch Polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar mybar -c ~/.config/polybar/config &

