#! /bin/sh

#launch key demon
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
#set ultrawide resolution
xrandr --output VGA-1 --mode 3440x1440 &
#set wallpaper
feh --bg-scale "$HOME/.config/wallpapers/mono.png" &

#defines monitors
bspc monitor -d terminal internet embedded debug files music misc

bspc config border_width            1
bspc config window_gap              10

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config normal_border_color     "#282C34"
bspc config focused_border_color    "#282C34"
bspc config presel_feedback_color   "#5C6370"

#startup applications
#bspc rule -a URxvt -o desktop=terminal state=floating rectangle=1152x600+70+70 && urxvt &
bspc rule -a URxvt -o desktop=terminal && urxvt &
bspc rule -a Firefox -o desktop=internet && firefox &
bspc rule -a URxvt -o desktop=embedded && urxvt -e nvim -O ~/Framework/test/{main,inits,interrupts}.c &

#launch Polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar mybar -r -c ~/.config/polybar/config &

